import type { Metadata } from "next";
import { Inter, Outfit, Oswald, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from "../components/Navbar";

const robotoCondensed = Roboto_Condensed({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={robotoCondensed.className}>
          <Navbar />
          {children}</body>
      </html>
    </ClerkProvider>
  );
}
